cities = [
    "Kabul", "Cairo","Alexandria","Herat", "Mazar-i-Sharif",
    "Tirana", "Durrës", "Vlorë",
    "Algiers", "Oran", "Constantine",
    "The Valley", "East End", "South Hill",
    "St. John's", "All Saints", "Jolly Harbour",
    "Buenos Aires", "Córdoba", "Rosario",
    "Oranjestad", "San Nicolaas", "Palm Beach",
    "Sydney", "Melbourne", "Brisbane",
    "Vienna", "Graz", "Salzburg",
    "Bridgetown", "Oistins", "Speightstown",
    "Brussels", "Antwerp", "Ghent",
    "Sarajevo", "Banja Luka", "Tuzla",
    "Gaborone", "Francistown", "Maun",
    "São Paulo", "Rio de Janeiro", "Brasília",
    "Sofia", "Plovdiv", "Varna",
    "Toronto", "Vancouver", "Montreal",
    "Bogotá", "Medellín", "Cali",
    "Zagreb", "Split", "Rijeka",
    "Nicosia", "Limassol", "Larnaca",
    "Prague", "Brno", "Ostrava",
    "Copenhagen", "Aarhus", "Odense",
    "Tallinn", "Tartu", "Narva",
    "Palikir", "Kolonia", "Weno",
    "Helsinki", "Espoo", "Tampere",
    "Paris", "Marseille", "Lyon",
    "Berlin", "Munich", "Hamburg",
    "Athens", "Thessaloniki", "Patras",
    "Georgetown", "New Amsterdam", "Linden",
    "Budapest", "Debrecen", "Szeged",
    "Reykjavík", "Akureyri", "Húsavík",
    "New Delhi", "Mumbai", "Bengaluru",
    "Jakarta", "Surabaya", "Medan",
    "Dublin", "Cork", "Limerick",
    "Jerusalem", "Tel Aviv", "Haifa",
    "Rome", "Milan", "Naples",
    "Kingston", "Montego Bay", "Ocho Rios",
    "Nairobi", "Mombasa", "Kisumu",
    "Kuwait City", "Jahra", "Ahmadi",
    "Riga", "Daugavpils", "Liepāja",
    "Vilnius", "Kaunas", "Klaipėda",
    "Luxembourg City", "Esch-sur-Alzette", "Differdange",
    "Antananarivo", "Toamasina", "Antsiranana",
    "Lilongwe", "Blantyre", "Mzuzu",
    "Valletta", "Sliema", "Birkirkara",
    "Majuro", "Ebeye", "Arno",
    "Mexico City", "Guadalajara", "Monterrey",
    "Chișinău", "Bălți", "Bender",
    "Ulaanbaatar", "Erdenet", "Darkhan",
    "Podgorica", "Nikšić", "Herceg Novi",
    "Yangon", "Mandalay", "Naypyidaw",
    "Amsterdam", "Rotterdam", "The Hague",
    "Auckland", "Wellington", "Christchurch",
    "Skopje", "Bitola", "Ohrid",
    "Oslo", "Bergen", "Stavanger",
    "Muscat", "Salalah", "Sohar",
    "Ngerulmud", "Koror", "Angaur",
    "Port Moresby", "Lae", "Mount Hagen",
    "Asunción", "Ciudad del Este", "Encarnación",
    "Manila", "Cebu City", "Davao City",
    "Warsaw", "Kraków", "Wrocław",
    "Lisbon", "Porto", "Coimbra",
    "Bucharest", "Cluj-Napoca", "Timișoara",
    "Moscow", "Saint Petersburg", "Novosibirsk",
    "Castries", "Vieux Fort", "Gros Islet",
    "Kingstown", "Bequia", "Union Island",
    "Apia", "Levao", "Faleasiu",
    "Dakar", "Touba", "Saint-Louis",
    "Belgrade", "Novi Sad", "Niš",
    "Bratislava", "Košice", "Nitra",
    "Ljubljana", "Maribor", "Celje",
    "Honiara", "Gizo", "Auki",
    "Cape Town", "Johannesburg", "Durban",
    "Madrid", "Barcelona", "Valencia",
    "Paramaribo", "Nieuw Nickerie", "Albina",
    "Stockholm", "Gothenburg", "Malmö",
    "Zurich", "Geneva", "Bern",
    "Dodoma", "Dar es Salaam", "Arusha",
    "Bangkok", "Chiang Mai", "Pattaya",
    "Nukuʻalofa", "Neiafu", "Vavaʻu",
    "Port of Spain", "San Fernando", "Scarborough",
    "London", "Birmingham", "Manchester",
    "New York", "Los Angeles", "Chicago",
    "Port Vila", "Luganville", "Espiritu Santo",
    "Harare", "Bulawayo", "Mutare"
]